/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProviderWalletRouteImport } from './routes/provider.wallet'
import { Route as ProviderProfileRouteImport } from './routes/provider.profile'
import { Route as ProviderOnboardingRouteImport } from './routes/provider.onboarding'
import { Route as ProviderJobsRouteImport } from './routes/provider.jobs'
import { Route as ProviderBidsRouteImport } from './routes/provider.bids'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerNewRouteImport } from './routes/customer.new'
import { Route as CustomerMessagesRouteImport } from './routes/customer.messages'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as CustomerRIdRouteImport } from './routes/customer.r.$id'

const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProviderWalletRoute = ProviderWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderProfileRoute = ProviderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderOnboardingRoute = ProviderOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderJobsRoute = ProviderJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderBidsRoute = ProviderBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => ProviderRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNewRoute = CustomerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerMessagesRoute = CustomerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerRIdRoute = CustomerRIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/customer': typeof CustomerRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/services': typeof AdminServicesRoute
  '/customer/messages': typeof CustomerMessagesRoute
  '/customer/new': typeof CustomerNewRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/provider/bids': typeof ProviderBidsRoute
  '/provider/jobs': typeof ProviderJobsRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/profile': typeof ProviderProfileRoute
  '/provider/wallet': typeof ProviderWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/customer/r/$id': typeof CustomerRIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/services': typeof AdminServicesRoute
  '/customer/messages': typeof CustomerMessagesRoute
  '/customer/new': typeof CustomerNewRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/provider/bids': typeof ProviderBidsRoute
  '/provider/jobs': typeof ProviderJobsRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/profile': typeof ProviderProfileRoute
  '/provider/wallet': typeof ProviderWalletRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/provider': typeof ProviderIndexRoute
  '/customer/r/$id': typeof CustomerRIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/customer': typeof CustomerRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/services': typeof AdminServicesRoute
  '/customer/messages': typeof CustomerMessagesRoute
  '/customer/new': typeof CustomerNewRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/provider/bids': typeof ProviderBidsRoute
  '/provider/jobs': typeof ProviderJobsRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/profile': typeof ProviderProfileRoute
  '/provider/wallet': typeof ProviderWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/customer/r/$id': typeof CustomerRIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/customer'
    | '/provider'
    | '/admin/analytics'
    | '/admin/disputes'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/services'
    | '/customer/messages'
    | '/customer/new'
    | '/customer/orders'
    | '/customer/profile'
    | '/provider/bids'
    | '/provider/jobs'
    | '/provider/onboarding'
    | '/provider/profile'
    | '/provider/wallet'
    | '/admin/'
    | '/customer/'
    | '/provider/'
    | '/customer/r/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/analytics'
    | '/admin/disputes'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/services'
    | '/customer/messages'
    | '/customer/new'
    | '/customer/orders'
    | '/customer/profile'
    | '/provider/bids'
    | '/provider/jobs'
    | '/provider/onboarding'
    | '/provider/profile'
    | '/provider/wallet'
    | '/admin'
    | '/customer'
    | '/provider'
    | '/customer/r/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/customer'
    | '/provider'
    | '/admin/analytics'
    | '/admin/disputes'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/services'
    | '/customer/messages'
    | '/customer/new'
    | '/customer/orders'
    | '/customer/profile'
    | '/provider/bids'
    | '/provider/jobs'
    | '/provider/onboarding'
    | '/provider/profile'
    | '/provider/wallet'
    | '/admin/'
    | '/customer/'
    | '/provider/'
    | '/customer/r/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  ProviderRoute: typeof ProviderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/provider/wallet': {
      id: '/provider/wallet'
      path: '/wallet'
      fullPath: '/provider/wallet'
      preLoaderRoute: typeof ProviderWalletRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/profile': {
      id: '/provider/profile'
      path: '/profile'
      fullPath: '/provider/profile'
      preLoaderRoute: typeof ProviderProfileRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/onboarding': {
      id: '/provider/onboarding'
      path: '/onboarding'
      fullPath: '/provider/onboarding'
      preLoaderRoute: typeof ProviderOnboardingRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/jobs': {
      id: '/provider/jobs'
      path: '/jobs'
      fullPath: '/provider/jobs'
      preLoaderRoute: typeof ProviderJobsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/bids': {
      id: '/provider/bids'
      path: '/bids'
      fullPath: '/provider/bids'
      preLoaderRoute: typeof ProviderBidsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/new': {
      id: '/customer/new'
      path: '/new'
      fullPath: '/customer/new'
      preLoaderRoute: typeof CustomerNewRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/messages': {
      id: '/customer/messages'
      path: '/messages'
      fullPath: '/customer/messages'
      preLoaderRoute: typeof CustomerMessagesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/r/$id': {
      id: '/customer/r/$id'
      path: '/r/$id'
      fullPath: '/customer/r/$id'
      preLoaderRoute: typeof CustomerRIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerMessagesRoute: typeof CustomerMessagesRoute
  CustomerNewRoute: typeof CustomerNewRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerRIdRoute: typeof CustomerRIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerMessagesRoute: CustomerMessagesRoute,
  CustomerNewRoute: CustomerNewRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerRIdRoute: CustomerRIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface ProviderRouteChildren {
  ProviderBidsRoute: typeof ProviderBidsRoute
  ProviderJobsRoute: typeof ProviderJobsRoute
  ProviderOnboardingRoute: typeof ProviderOnboardingRoute
  ProviderProfileRoute: typeof ProviderProfileRoute
  ProviderWalletRoute: typeof ProviderWalletRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderBidsRoute: ProviderBidsRoute,
  ProviderJobsRoute: ProviderJobsRoute,
  ProviderOnboardingRoute: ProviderOnboardingRoute,
  ProviderProfileRoute: ProviderProfileRoute,
  ProviderWalletRoute: ProviderWalletRoute,
  ProviderIndexRoute: ProviderIndexRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CustomerRoute: CustomerRouteWithChildren,
  ProviderRoute: ProviderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
